### ISSUE TITLE
Hash algorithm choices, FIPS compliance

### ISSUE THREAD

**Issue by hyc** [tevador/RandomJS#11]
While at DefCon in August, we had several conversations with some folks who work at the DoD. One interesting story they passed along was that they were unable to use the Ethereum codebase as-is because it was using (among other things) Keccak instead of the finalized SHA-3 spec. The point of the story being, we should consider using NIST standardized hash mechanisms if we want to ensure the widest possible acceptance and deployment of our work.

**Comment by timolson** [comment]
Just use SHA-3 and accept the inevitability of ASIC’s!

The way to ensure fair access to miners is to use a PoW which is commoditized and widely available near cost.  This requires a low barrier to entry for miner startups, meaning the PoW needs to be simple and well-studied.  Complex PoW’s like CryptoNight or RandomJS, even an S-box hash like SHA-2, have high barriers to entry for new manufacturers and have many subtle optimizations that lead to the dominance of only one or a few proprietary implementations.

SHA-3 has many advantages: The fact that it is simple to implement in hardware and would have strong demand in markets outside crypto means that the SHA-3 chip market would be quickly commoditized with multiple vendors in multiple markets.  As a bonus, Keccak is very fast and efficient in hardware, much faster than any other SHA-3 candidate.

**Comment by hyc** [comment]
1) Yes, I'm suggesting we should use SHA-3 and not Keccak or Blake2b in randomJS.

2) We're years and years away from PoW being commoditized to any meaningful degree. Until then, average users aren't going to go out of their way to buy mining chips/rigs. The only way to make sure average users are mining is to use hardware they already have in their homes/offices/pockets. Maybe eventually someone will develop a JS accelerator chip that's so useful that it will start being integrated into PC and smartphone CPUs. But that day is a long way off.

**Comment by timolson** [comment]
> We're years and years away from PoW being commoditized to any meaningful degree.

I must disagree.
After the boom of late 2017, a bunch of new competitors popped up.  Barrier to entry for SHA chips is significant but not overwhelming, and BitMain is already behind.  WhatsMiner is now **50% more efficient** at the 16nm node and IMO the days of viewing BitMain as a monopoly are already over. ASIC miners are quickly becoming commodities.  Now.  This year.

**Comment by tevador** [comment]
Blake2b was chosen because it's fast in software (especially on OoO processors).

For SHA3, the performance per watt difference between ASIC and CPU is much higher (order of magnitude). Actually the performance of SHA3 in hardware was one of the reasons why it won the competition.

For an ASIC-friendly PoW, I support SHA3 without objections.

**Comment by hyc** [comment]
OK, I'd forgotten you've said this before. Still wanted the notion of standards-compliance to get noted.
